project:
  type: book
  output-dir: _book

book:
  title: "Size ecology lab notebook"
  reader-mode: true

  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#cover-image: cover.png
#favicon: cover.png
#site-url:
#repo-url:
#repo-branch: main
#repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - sizeecology.qmd
    - part: toolsintro.qmd
      chapters:
        - usefultools.qmd
format:
  html:
    theme:
      - cosmo

    code-link: true

    author-meta: "Size ecology lab members"
    include-in-header: "publishquartobook.html"
    callout-appearance: simple

editor: visual

