project:
  type: book
  output-dir: docs

book:
  title: "Size ecology lab notebook"
  reader-mode: true


  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#cover-image: cover.png
#favicon: cover.png
#site-url:
#repo-url:
#repo-branch: main
#repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - usefullinks.qmd
    - codeofconduct.qmd
    - sizeecology.qmd
    - part: researchapproaches.qmd
      chapters:
        - reproduciblescience.qmd
        - collabresources.qmd
    - part: ecomodelling.qmd
      chapters:
        - mizer.qmd
        - thermizer.qmd
        - fishMIP.qmd
        - globalecology.qmd
    - part: exptresearch.qmd
      chapters:
        - aquaculturemodelling.qmd
    - part: fieldresearch.qmd
      chapters:
        - aquaculturetrials.qmd
    - part: commsintro.qmd
      chapters:
        - scicomm.qmd
        - datatools.qmd

format:
  html:
    theme:
      - flatly

    code-link: true

    author-meta: "Size ecology lab members"
    include-in-header: "publishquartobook.html"
    callout-appearance: simple

editor: visual

